version: '3.7'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=matt_perry1@yahoo.com
      - PGADMIN_DEFAULT_PASSWORD=s3cret
       